# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./fastapi
    container_name: ai_product_fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./streamlit
    container_name: ai_product_streamlit
    ports:
      - "8500:8500"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
